config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :questions do
    resources :answers, shallow: true
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def author?(resource)
    id == resource.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[index new show create]
  before_action :load_answer, only: %i[show destroy]

  def index
    @answers = @question.answers
  end

  def new
    @answer = @question.answers.new
  end

  def show; end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      redirect_to @question, notice: 'Your answer successfully created.'
    else
      render 'questions/show'
    end
  end

  def destroy
    if current_user.author?(@answer)
      @answer.destroy
      redirect_to question_path(@answer.question), notice: 'Your answer successfully delete.'
    else
      redirect_to @answer
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Your question successfully delete.'
    else
      redirect_to @question
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.slim
= render 'shared/errors', resource: @answer

- if current_user.present?
= form_for [@question, @answer] do |f|
  = f.label :body
  = f.text_area :body
  = f.submit 'Create answer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.slim
- @questions.each do |question|
  = link_to question.title, question_path(question)
  br
p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body
- if current_user&.author?(@question)
  p= link_to 'Delete question', question_path(@question), method: :delete

h2 Answers

- @question.answers.each do |answer|
  - if answer.persisted?
    p.answer= answer.body
    - if current_user&.author?(answer)
      p= link_to 'Delete answer', answer_path(answer), method: :delete

  = render 'answers/form'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b="#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
- if user_signed_in?
  = link_to 'Sign out', destroy_user_session_path, method: :delete
-else
  = link_to 'Login', new_user_session_path
  br
  = link_to 'Registration', new_user_registration_path